Warsztat programowanie obiektowe/Models/MendingModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Warsztat_programowanie_obiektowe.Models
{
    public class MendingModel
    {
        [Key]
        public int ID_mending { get; set; }
        public virtual ICollection<WorkersModel> Worker { get; set; }
        public virtual ICollection<CarModel> Car { get; set; }
        public virtual IEnumerable<PartModel> List { get; set; }
        public DateTime MendingDate { get; set; }
        public float MendingTime { get; set; }
        public string MendingState { get; set; }
        public string VIN { get; set; }
        public int ID_worker { get; set; }
    }
}

Warsztat programowanie obiektowe/Controllers/MendingModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Warsztat_programowanie_obiektowe.Models;

namespace Warsztat_programowanie_obiektowe.Controllers
{
    public class MendingModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MendingModels
        public ActionResult Index()
        {
            return View(db.mendings.ToList());
        }

        public ActionResult List(int? id)
        {
            MendingModel mending = db.mendings.Single(p => p.ID_mending == id);
            var allList = db.mendignList.ToList();
            var list = allList.Where(p => p.ID_mending == id);
            var parts = db.parts.ToList();
            mending.List = parts.Where(p => list.Any(q=> q.ID_part==p.ID_part));
            PopulatePartsDropDownList();
            return View(mending);
        }
        [HttpPost]
        public ActionResult ListAdd ([Bind(Include = "ID_mending,ID_part")] MendingListModel mendingListModel)
        {
            db.mendignList.Add(mendingListModel);
            var partNO = mendingListModel.ID_part;
            PartModel part = db.parts.Find(partNO);
            part.Stock = part.Stock - 1;
            db.Entry(part).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: MendingModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MendingModel mendingModel = db.mendings.Find(id);
            if (mendingModel == null)
            {
                return HttpNotFound();
            }
            return View(mendingModel);
        }

        // GET: MendingModels/Create
        public ActionResult Create()
        {

            PopulateCarsDropDownList();
            return View();
            
        }

        // POST: MendingModels/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_mending,VIN,MendingDate,MendingTime,ID_worker,MendingState")] MendingModel mendingModel)
        {
            if (ModelState.IsValid)
            {
                db.mendings.Add(mendingModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            PopulateCarsDropDownList(mendingModel.VIN);

            return View(mendingModel);
        }

        // GET: MendingModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MendingModel mendingModel = db.mendings.Find(id);
            if (mendingModel == null)
            {
                return HttpNotFound();
            }
            PopulateCarsDropDownList();
            return View(mendingModel);
        }

        // POST: MendingModels/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_mending,VIN,MendingDate,MendingTime,ID_worker,MendingState")] MendingModel mendingModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mendingModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulateCarsDropDownList(mendingModel.VIN);
            return View(mendingModel);
        }

        // GET: MendingModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MendingModel mendingModel = db.mendings.Find(id);
            if (mendingModel == null)
            {
                return HttpNotFound();
            }
            return View(mendingModel);
        }

        // POST: MendingModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MendingModel mendingModel = db.mendings.Find(id);
            db.mendings.Remove(mendingModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void PopulateCarsDropDownList(object selectCar = null)
        {
            var carQuery = from d in db.cars
                                  orderby d.Year
                                  select d;
            ViewBag.VIN = new SelectList(carQuery, "VIN", null, selectCar);
        }

        private void PopulatePartsDropDownList(object selectPart = null)
        {
            var partQuery = from d in db.parts
                           orderby d.Name
                           select d;
            ViewBag.ID_part = new SelectList(partQuery, "ID_part", "Name", selectPart);
        }


    }
}

Warsztat programowanie obiektowe/Views/MendingModels/Create.cshtml
@model Warsztat_programowanie_obiektowe.Models.MendingModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    var list = new List<string>();
    list.Add("W trakcie");
    list.Add("naprawiono");

    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>MendingModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MendingDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MendingDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MendingDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VIN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("VIN", String.Empty)
            @Html.ValidationMessageFor(model => model.VIN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MendingTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MendingTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MendingTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ID_worker, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ID_worker, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ID_worker, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MendingState, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model=> model.MendingState, new SelectList(list))
            @Html.ValidationMessageFor(model => model.ID_worker, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Warsztat programowanie obiektowe/Views/MendingModels/Delete.cshtml
@model Warsztat_programowanie_obiektowe.Models.MendingModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MendingModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MendingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MendingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MendingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MendingTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Warsztat programowanie obiektowe/Views/MendingModels/Details.cshtml
@model Warsztat_programowanie_obiektowe.Models.MendingModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MendingModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MendingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MendingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MendingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MendingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VIN)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ID_worker)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_worker)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_mending }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Warsztat programowanie obiektowe/Views/MendingModels/Edit.cshtml
@model Warsztat_programowanie_obiektowe.Models.MendingModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    var list = new List<string>();
    list.Add("W trakcie");
    list.Add("naprawiono");

    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>MendingModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_mending)

    <div class="form-group">
        @Html.LabelFor(model => model.MendingDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MendingDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MendingDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VIN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("VIN", String.Empty)
            @Html.ValidationMessageFor(model => model.VIN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MendingTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MendingTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MendingTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ID_worker, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ID_worker, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ID_worker, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MendingState, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.MendingState, new SelectList(list))
            @Html.ValidationMessageFor(model => model.ID_worker, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Warsztat programowanie obiektowe/Views/MendingModels/Index.cshtml
@model IEnumerable<Warsztat_programowanie_obiektowe.Models.MendingModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MendingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MendingTime)
        </th>
        <th>
            ID pracownika
        </th>
        <th>
            Lista
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.MendingDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MendingTime)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ID_worker)
    </td>
    <td>
        @Html.ActionLink("Pokaz liste", "List", new { id= item.ID_mending})
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID_mending }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID_mending }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID_mending })
    </td>
</tr>
}

</table>

Warsztat programowanie obiektowe/Views/MendingModels/List.cshtml
@model Warsztat_programowanie_obiektowe.Models.MendingModel

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>

<div>
    <h4>MendingModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MendingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MendingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MendingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MendingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_worker)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_worker)
        </dd>
    </dl>
    <table class="table">
        <tr>
            <th>
            <th>
                @Html.ActionLink("Nazwa", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Cena", "Index", new { sortOrder = ViewBag.PriceSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.List)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID_part }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID_part }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID_part })
                </td>
            </tr>
        }
    </table>

    @using (Html.BeginForm("ListAdd", "MendingModels"))
    {

        <div class="form-group">
            @Html.LabelFor(model => model.ID_mending, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_mending);
                @Html.ValidationMessageFor(model => model.ID_mending, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <lable class = "control-label col-md-2"> ID_part</lable>
            <div class="col-md-10">
                @Html.DropDownList("ID_part", String.Empty)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    }
    @Html.ActionLink("Dodaj czesc do listy", "ListAdd", new { id = Model.ID_mending });
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_mending }) |
    @Html.ActionLink("Back to List", "Index")
</p>