Warsztat programowanie obiektowe/Models/PartModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Warsztat_programowanie_obiektowe.Models
{
    public class PartModel
    {
        [Key]
        public int ID_part { get; set; }
        public string Name { get; set; }
        public float Price { get; set; }
        public int Stock { get; set; }
        public int ID_dealer { get; set; }
        public virtual ICollection<DealerModel> Dealer { get; set; }
       
    }
}

Warsztat programowanie obiektowe/Controllers/DealerModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Warsztat_programowanie_obiektowe.Models;

namespace Warsztat_programowanie_obiektowe.Controllers
{
    public class DealerModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DealerModels
        public ActionResult Index()
        {
            return View(db.dealers.ToList());
        }

        // GET: DealerModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DealerModel dealerModel = db.dealers.Find(id);
            if (dealerModel == null)
            {
                return HttpNotFound();
            }
            return View(dealerModel);
        }

        // GET: DealerModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DealerModels/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_dealer,Name,PhoneNo,NIP")] DealerModel dealerModel)
        {
            if (ModelState.IsValid)
            {
                db.dealers.Add(dealerModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dealerModel);
        }

        // GET: DealerModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DealerModel dealerModel = db.dealers.Find(id);
            if (dealerModel == null)
            {
                return HttpNotFound();
            }
            return View(dealerModel);
        }

        // POST: DealerModels/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_dealer,Name,PhoneNo,NIP")] DealerModel dealerModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dealerModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dealerModel);
        }

        // GET: DealerModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DealerModel dealerModel = db.dealers.Find(id);
            if (dealerModel == null)
            {
                return HttpNotFound();
            }
            return View(dealerModel);
        }

        // POST: DealerModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DealerModel dealerModel = db.dealers.Find(id);
            db.dealers.Remove(dealerModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Warsztat programowanie obiektowe/Controllers/PartModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Warsztat_programowanie_obiektowe.Models;
using PagedList;

namespace Warsztat_programowanie_obiektowe.Controllers
{
    public class PartModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PartModels
        public ActionResult Index(string sortOrder,  int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParam = sortOrder == "Price" ? "price_desc" : "Price";

            var parts = from p in db.parts select p;

            switch (sortOrder)
            {

                case "name_desc":
                    parts = parts.OrderByDescending(s => s.Name);
                    break;
                case "Price":
                    parts = parts.OrderBy(p => p.Price);
                    break;
                case "price_desc":
                    parts = parts.OrderByDescending(p => p.Price);
                    break;
                default:
                    parts = parts.OrderBy(p => p.Name);
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);


            return View(parts.ToPagedList(pageNumber, pageSize));

        }

        // GET: PartModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartModel partModel = db.parts.Find(id);
            if (partModel == null)
            {
                return HttpNotFound();
            }
            return View(partModel);
        }

        // GET: PartModels/Create
        public ActionResult Create()
        {
            PopulateDealersDropDownList();

            return View();
        }

        // POST: PartModels/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_part,Name,Price,ID_dealer")] PartModel partModel)
        {
            if (ModelState.IsValid)
            {
                db.parts.Add(partModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateDealersDropDownList(partModel.ID_dealer);
            return View(partModel);
        }

        // GET: PartModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartModel partModel = db.parts.Find(id);
            if (partModel == null)
            {
                return HttpNotFound();
            }
            PopulateDealersDropDownList(partModel.ID_dealer);
            return View(partModel);
        }

        // POST: PartModels/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_part,Name,Stock,Price,ID_dealer")] PartModel partModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(partModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
                PopulateDealersDropDownList(partModel.ID_dealer);

                return View(partModel);

        }

        // GET: PartModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartModel partModel = db.parts.Find(id);
            if (partModel == null)
            {
                return HttpNotFound();
            }
            return View(partModel);
        }

        // POST: PartModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PartModel partModel = db.parts.Find(id);
            db.parts.Remove(partModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void PopulateDealersDropDownList(object selectDdealer = null)
        {
            var dealerQuery = from d in db.dealers
                            orderby d.Name
                            select d;
            ViewBag.ID_dealer = new SelectList(dealerQuery, "ID_dealer", "Name", selectDdealer);
        }
    }
}

Warsztat programowanie obiektowe/Views/PartModels/Create.cshtml
@model Warsztat_programowanie_obiektowe.Models.PartModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PartModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ID_dealer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_dealer", String.Empty)
            @Html.ValidationMessageFor(model => model.ID_dealer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Warsztat programowanie obiektowe/Views/PartModels/Delete.cshtml
@model Warsztat_programowanie_obiektowe.Models.PartModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PartModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Warsztat programowanie obiektowe/Views/PartModels/Details.cshtml
@model Warsztat_programowanie_obiektowe.Models.PartModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PartModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_part }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Warsztat programowanie obiektowe/Views/PartModels/Edit.cshtml
@model Warsztat_programowanie_obiektowe.Models.PartModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PartModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_part)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ID_dealer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_dealer", String.Empty)
            @Html.ValidationMessageFor(model => model.ID_dealer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Warsztat programowanie obiektowe/Views/PartModels/Index.cshtml
@model PagedList.IPagedList<Warsztat_programowanie_obiektowe.Models.PartModel>
@using PagedList.Mvc,
@using Warsztat_programowanie_obiektowe.Models,
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework,




<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@{
    ApplicationDbContext db = new ApplicationDbContext();

    var listOfUsers = (from u in db.Users
                       let query = (from ur in db.Set<IdentityUserRole>()
                                    where ur.UserId.Equals(u.Id)
                                    join r in db.Roles on ur.RoleId equals r.Id
                                    select r.Name)
                       select new UserRoleInfo() { User = u, Roles = query.ToList<string>() })
                 .ToList();


    var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>());
    var userRole = listOfUsers.Where(p => p.User.Id == User.Identity.GetUserId());



    if (userRole.First().Roles.Contains("SuperAdmin"))
    {
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    }
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Nazwa", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Cena", "Index", new { sortOrder = ViewBag.PriceSortParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            ID Hurtowni
        </th>
        <th>
            Ilosc
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Price)
    </td>
    <td>
        @Html.ActionLink(item.ID_dealer.ToString(), "Details", "DealerModels", new { id = item.ID_dealer }, "")
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Stock)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID_part }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID_part }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID_part })
    </td>
</tr>
    }

</table>
        </br>
        Page @(Model.PageCount < Model.PageNumber ? 0  : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSosrt }))